### PR TITLE
Cmake target

### PR DESCRIPTION
**Pull request by Ansoulom**
I've modified the CMakeLists.txt to add an actual library target for the library. In addition, I've added install and export statements so that a user can properly install the library onto their system, either manually with `cmake --build . --target install` or via a package manager.

The previous version of the CMakeLists.txt file doesn't play nice with the regular CMake workflow for a user, in which the user should simply be able to add
```
find_package(fx-gltf 1.0.1 REQUIRED)
target_link_libraries(mytarget PRIVATE fx-gltf::fx-gltf)
```
to their own CMakeLists.txt, after the library has been installed onto the system.
This workflow is now properly supported from this pull request. In addition, CMake will be able to automatically resolve the dependency to nlohmann_json without the user having to mention it in their CMakeLists.txt (the only requirement is again that nlohmann_json is installed onto the user's system).

I've also changed the CMakeLists.txt for the tests to follow the same best practice CMake workflow, with `find_package` and `target_link_libraries`. While this doesn't really matter for a user of the library, I thought it just made sense to do this. It also allowed for getting rid of the third-party dependencies from the repo.

Also, to make it even easier for users to use this library, I might make another pull request to add support for exporting the library as a Conan package. Think I'll make a separate issue for that though.

### CODE REVIEW

**Comment by Ansoulom** [comment]
So I realized that the CI builds fail now due to the dependencies to nlohmann_json and Catch2 not being correctly resolved in the CI. Unfortunately, I don't have any experience neither with appveyor nor travis, so I don't know exactly how to fix this... With that said, it should certainly be possible as I would imagine that CMake and its recommended workflow should be well supported.

**Comment by Ansoulom** [comment]
One way to resolve the dependencies in the CI is by using Conan, as outlined here:
https://docs.conan.io/en/latest/integrations/appveyor.html
https://docs.conan.io/en/latest/integrations/travisci.html

This seems pretty straightforward and would only require some modifications to `.travis.yml`, `appveyor.yml`, as well as the addition of a `conanfile.txt` file. Note that the project can still be built without Conan, as long as the unintrusive [cmake_paths](https://docs.conan.io/en/latest/integrations/cmake/cmake_paths_generator.html) Conan generator is used.

If you want, I could add this to the pull request. Or if you have another way that you would rather resolve the dependencies in the CI, that's fine too.

**Comment by jessey-git** [comment]
Hey thanks for looking into this and contributing!  I'll admit that I'm not the best at cmake (which is why this stuff wasn't there to begin with) but I'll try to review this more in depth during the week.

In general I definitely want to keep the main install targets you added.

However, for the tests, the idea was to make the repo completely self contained and to allow easier development when new versions of those dependencies come out (without having to install them etc.).  e.g. if a new version of json comes out I can quickly try it out here (or not) without installing it in a more official manner.

Thoughts?  If you agree, would you mind splitting the PR into 2 parts: the part for the main library install targets and another for the tests?  At that point we can try playing around with perhaps just making the Catch2 dependency cmake friendly and leaving json to be part of the repo.

**Comment by Ansoulom** [comment]
I can absolutely see where you're coming from with wanting to make it self contained. Personally, I've given up on doing that with my projects and am just using a package manager for everything instead (it's really easy to change which version of a library you want the project to use in Conan for example). But as you are the one actually working on this project, I shouldn't be one to disrupt your preferred workflow.

As for avoiding to make the use of the json library CMake friendly, I can see a problem with that. Ideally, you don't want your users to have to specify in their `CMakeLists.txt` that they want to use nlohmann_json. The users want to use fx-gltf, not nlohmann_json, so the json dependency should be resolved without them having to specify it. This requires that the exported target is properly linked to the nlohmann_json target before it is exported, which in turn requires `find_package(nlohmann_json)` to be present in the library's `CMakeLists.txt`.

It is however possible to achieve this, while still keeping your self-contained workflow, by adding an option for if targets should be exported or not and having an `if` directive inside the CMake file. This way you could simply set an option from the command line when building the library and the third-party dependencies wouldn't have to be installed on the system if this option is set to the right value.

If you want to understand the CMake stuff that's in this PR a bit better, I would recommend reading [this blog post](https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/).

**Comment by jessey-git** [comment]
Yes, right, keeping the required dependencies like json in the main targets is fine I think.  That way users can just use fx-gltf and get what they need.  It's just for the test project I'd like to keep the thirdparty workflow.

**Comment by Ansoulom** [comment]
I have now added two options to the CMake files. The first one is `FX_GLTF_INSTALL`, which simply determines if the library should be installed or not. The second one is `FX_GLTF_USE_INSTALLED_DEPS` which determines if dependencies installed on the system or the dependencies in the repo should be used.

`FX_GLTF_USE_INSTALLED_DEPS` gets forced to `ON` if `FX_GLTF_INSTALL` is on, as it doesn't make much sense to install with the repo dependencies.

`FX_GLTF_INSTALL` is currently `ON` by default, so you'll have to set it to `OFF` to avoid installing on build and to use the repo local deps.

Does this sound reasonable? The CI succeeds now anyway (I've added `-DFX_GLTF_INSTALL=OFF` to the CI config files).

**Comment by jessey-git** [comment]
Cool, thanks for this!  I've gone ahead and merged this in.

**Comment by Ansoulom** [comment]
Great, thanks for accepting the PR!

**Pull request merged**
